alias ls="ls -GF"
alias ll="ls -l"
alias la="ll -a"
alias beep="echo -e \"\a\""

alias gfp="git fetch && git pull"

eval "$(starship init bash)"
eval "$(direnv hook bash)"

# add local specific profile settings, if needed
if [ -f ~/.bashrc.local ]; then
    . ~/.bashrc.local
fi
