# default programs
export EDITOR="nvim"

# follow XDG base dir specs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"


# add local specific profile settings, if needed
if [ -f ~/.bash_profile.local ]; then
    . ~/.bash_profile.local
fi
