if [ -f ~/dotfiles/config/shell-aliases ]; then
    source ~/dotfiles/config/shell-aliases
fi
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init zsh)"
fi
if command -v direnv >/dev/null 2>&1; then
    eval "$(direnv hook zsh)"
fi
if [ -f "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

# add local specific profile settings, if needed
if [ -f ~/.bashrc.local ]; then
    . ~/.bashrc.local
fi
