# .zprofile
# - for environment variables, configuration

# use vim keybindings when navigating history
set -o vi

# default programs
export EDITOR=nvim
export TERM="tmux-256color"

# follow XDG base dir specs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Set PATH, MANPATH, etc., for macOS machines
if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# add local specific profile settings, if needed
if [ -f ~/.zprofile.local ]; then
    source ~/.zprofile.local
fi
